### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by melihaksoy** [melihaksoy/Android-Kotlin-Modulerized-CleanArchitecture#22]
Need to add search functionality that runs on different feature, that will present query results in a separate list. We should use [https://launchlibrary.net/1.4/launch](launch) method - there are examples under section.

Documentation: https://launchlibrary.net/docs/1.4.1/api.html

**Comment by bansalayush** [comment]
@melihaksoy  Are you looking for maintainers ?

**Comment by melihaksoy** [comment]
@bansalayush For sure, it'd be nice to have contributions. I have some other features in mind that I need to create in issue list, before this repo actually starts represents a all-around example.

**Comment by bansalayush** [comment]
I didn't get `fetching search data rather than searching through paged data` part. Can you help me out ?

**Comment by melihaksoy** [comment]
I just updated description. I think UX wise having a separate feature for search is not a bad idea - just like launches & detail - this may come in handy in terms of decoupling.

**Comment by melihaksoy** [comment]
Closing this as it'll be part of #21.
